CREATE TABLE users (
                       user_id SERIAL PRIMARY KEY,
                       username VARCHAR(50) UNIQUE NOT NULL,
                       email VARCHAR(100) UNIQUE NOT NULL ,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create table route
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    name        varchar(255) not null
);
-- CREATE EXTENSION postgis;
create table stop
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    latitude    double precision not null,
    longitude   double precision not null,
    name        varchar(255)     not null,
    stop_type   varchar(255),
    route_id    bigint           not null
        constraint fkdlo2jg2ydpg8cicshnqn7v4ex
            references route
);

-- CREATE INDEX idx_stops_location ON stop USING GIST (location);
